#pragma once

#include "ArduCAM.h"
#include "baro_thermo_hygrometer.hpp"
#include "Camera2.h"
#include "cds.hpp"
#include "computer.hpp"
#include "DCMotor.h"
#include "GPS.h"
#include "imu.hpp"
#include "memorysaver.h"
#include "Microphone.h"
#include "PIN_ASSIGN.h"
#include "SD.h"
#include "Servo.h"
#include "ultrasonic_distance_sensor.hpp"
#include "xbee.hpp"
