#pragma once

#include "ArduCAM.h"
#include "BarometerThermohygrometer.h"
#include "Camera2.h"
#include "computer.hpp"
#include "DCMotor.h"
#include "GPS.h"
#include "IMU.h"
#include "Light.h"
#include "memorysaver.h"
#include "Microphone.h"
#include "PIN_ASSIGN.h"
#include "SD.h"
#include "Servo.h"
#include "UltrasonicDistanceSensor.h"
#include "xbee.hpp"
