name: Generate Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/generate-labels.yaml'
      - '.github/labels/label-definition.yaml'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - '.github/workflows/generate-labels.yaml'
      - '.github/labels/label-definition.yaml'

jobs:

  labeler:
    name: labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels/label-definition.yaml
          skip-delete: false
          dry-run: false
